server:
  port: 8020
spring:
  application:
    name: order-nacos
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
